services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"      # UI
      - "50000:50000"    # JNLP agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # чтобы Jenkins мог управлять Docker
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net: